import React from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import FoodList from './FoodList';
import Filter from './Filter';
import { useState } from 'react';
import Description from "./Description"
import './App.css';
import { BrowserRouter, Route, Switch } from "react-router-dom";
import cover from './Res/background.jpg';
import photo1 from "./Res/photo1.jpg"
import photo2 from "./Res/photo2.jpg"
import photo3 from "./Res/photo3.jpg"
import photo4 from "./Res/photo4.jpg"
import photo5 from "./Res/photo5.jpg"
import photo6 from "./Res/photo6.jpg"
import photo7 from "./Res/photo7.jpg"
import photo8 from "./Res/photo8.jpg"
import photo9 from "./Res/photo9.jpg"
import photo10 from "./Res/photo10.jpg"
import photo11 from "./Res/photo11.jpg"
import photo12 from "./Res/photo12.jpg"
import photo13 from "./Res/photo13.jpg"
import photo14 from "./Res/photo14.jpg"
import photo15 from "./Res/photo15.jpg"
import photo16 from "./Res/photo16.jpg"
import photo17 from "./Res/photo17.jpg"
import photo18 from "./Res/photo18.jpg"
import photo19 from "./Res/photo19.jpg"
import photo20 from "./Res/photo20.jpg"
import photo21 from "./Res/photo21.jpg"
import photo22 from "./Res/photo22.jpg"
import photo23 from "./Res/photo23.jpg"
import photo24 from "./Res/photo24.jpg"
import photo25 from "./Res/photo25.jpg"
import photo26 from "./Res/photo26.jpg"
import photo27 from "./Res/photo27.jpg"
function App() {
  const objFood=[
    { id:1, title:"Baked tomatoes with feta ", ingredients:"4 pounds cocktail, roma, plum, or cherry tomatoes · 2 tablespoons extra virgin olive oil · 6-8 cloves whole garlic · 1/2 teaspoon kosher salt · 1/2 teaspoon ", describe:"Make your own dukkah spice mix to sprinkle over tomatoes and feta, or buy a ready-made version if you prefer. Serve with sesame flatbreads", img:photo1, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/LuroDGsJkMA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:2, title:"Spinach & cheese pide", ingredients:"450 grams plain flour. 1 tbsp dry yeast. 1 tbsp honey. 250 ml body temp lukewarm water. 2 tbsps olive oil.2 teaspoons salt.", describe:"Make our version of Turkish pide with spinach and goat’s cheese, ideal for a light lunch or picnic. Pide are boat-shaped flatbreads that are filled and baked", img:photo2, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/f5WGsIFELtU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:3, title:"Malfatti", ingredients:"1 kg d'épinards. 250 g de ricotta. 30 g de farine. 2 œufs. 50 g de parmesan râpéSel, poivre. Muscade.",describe:"Make our take on Tuscan malfatti – spinach and ricotta dumplings that look a bit like large, roughly formed gnocchi. Serve coated in an aromatic sage butter and plenty of cheese", img:photo3, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/JKbGCAjuvVo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:4, title:"Harissa fish pie", ingredients:"700g sweet potatoes (3-4 small ones or 2 large ones) 3 tbsp rapeseed oil. pinch of cumin. pinch of smoked paprika. 1 onion, finely chopped. 1 red pepper, finely chopped. 350ml semi-skimmed milk. 350g fish pie mix ", describe:"Add harissa to fish pie and top with sweet potato for a twist on a classic. Nutritionally balanced and filling, it’s ideal for a family meal", img:photo4, rate:2, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/cowbykzcRVk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:5, title:"Sweet potato balls",ingredients:"Tapioca flour (50g). Sugar (20g)", describe:"Make a Taiwanese snack favourite, sweet potato balls. They’re made with sweet potato and tapioca starch, rolled into balls and deep-fried until golden brown", img:photo5, rate:2, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/smPF8270wj4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:6, title:"Carrot & parsnip soup",ingredients:"2 tbsp vegetable oil. 1 large or 2 medium onions, chopped. 500g carrots, roughly chopped. 500g parsnips, roughly chopped. 1 tsp ground turmeric, optional. 1 tbsp ground coriander. 40g root ginger, chopped.", describe:"Create a batch of creamy parsnip and carrot soup for a warming lunch or supper. Serve with crusty bread and freeze any leftovers you have for busy days", img:photo6, rate:1, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/ZiilnqfkTeM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:7, title:"Winter tabbouleh", ingredients:"Winter tabbouleh",describe:"Combine cauliflower, fennel, bulgur wheat, nuts and pomegranate seeds to make this winter version of tabbouleh. It’s delicious served as a side dish", img:photo7, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/msHIwdXplj4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:8, title:"Pizza with homemade sauce",ingredients:"15 lbs tomatoes I used mostly Roma.2 onions medium - chopped.1 red bell pepper chopped.5 cloves garlic minced.1 tbsp vegetable oil.2 tbsp fresh basil.1 tsp salt.", describe:"Make pizza for the family with a homemade base and tomato sauce. The recipe is perfect to get kids involved in cooking. Top with mozzarella and fresh basil", img:photo8, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/gd72Qg6ns2M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:9, title:"Glamorgan sausages",ingredients:"15g/4oz leeks, trimmed, finely sliced (prepared weight) · 175g/6oz fresh white breadcrumbs · 2 tbsp chopped fresh parsley ·", describe:"Make your own Glamorgan sausages, a traditional Welsh vegetarian sausage featuring cheese, leeks and breadcrumbs. Make a batch of 12 and freeze any you don’t eat", img:photo9, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/xMmfI-Og3jw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:10, title:"Salsa verde salmon with smashed chickpea salad",ingredients:"4 green onions, cut into pieces; 1 jalapeño, seeded; 1 garlic clove, peeled; 1/2 cup (125 ml) cilantro", describe:"Serve up this healthy salsa verde salmon with smashed chickpea, kale and roasted red pepper salad for a quick ", img:photo10, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/WVZcIuxMnVM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:11, title:"Cheese & spinach penne with walnut crumble",ingredients:"25g/1oz butter · 1500g pack penne. 2 large leeks , sliced. 85g butter. 85g plain flour. 2 tsp ready-made English mustard. good grating nutmeg. 1l milk , plus a bit extra. 350g pack mature cheddar , grated.", describe:" A twist on macaroni cheese, with added veg and a crunchy topping of bread and nuts – make in batches and freeze with Cheese & spinach penne with walnut crumble", img:photo11, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/G41x_QzQGII" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:12, title:"Spinach filo spiral pie",ingredients:"54%, onion 28%, modified potato starch, non-hydrogenated vegetable oils (sunflower seed oil, cotton seed oil, palm oil), extra virgin olive oil 2%, modified corn starch, salt, dill 0.5%, garlic dehydrated.", describe:"These impressive-looking spinach filo spirals are deceptively easy to make. A take on Greek spanakopita, serve with a side salad for a weekend lunch", img:photo12, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/G1lypSlxU8o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:13, title:"Smoked brisket",ingredients:"12 to 14 lb prime grade beef brisket flat and point (fat trimmed to 1/4”) 1/2 cup diamond kosher salt. 1/2 cup freshly ground black pepper. post oak and apple wood chunks for smoking.", describe:"Fire up the smoker for this flavourful slow-cooked brisket. Serve on a board with charred greens and salsa rossa so everyone can help themselves", img:photo13, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/Dn5ZJz2Ta78" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:14, title:"Mulligatawny soup",ingredients:"15 lbs tomatoes I used mostly Roma.2 onions medium - chopped.1 red bell pepper chopped.5 cloves garlic minced.1 tbsp vegetable oil.2 tbsp fresh basil.1 tsp salt.", describe:"Cook a batch of mulligatawny soup, packed with veg and rice and gently spiced with curry powder and spices. Top with coriander and yogurt", img:photo14, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/F0vbd0tT0DQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:15, title:"Courgette & cheddar cornbread", ingredients:"8. 125g coarsely chopped courgette; 235ml milk; 85g chopped onion; 2 eggs; 60ml vegetable oil; 170g dry polenta (cornmeal). 125g plain",describe:"Enjoy this cheesy cornbread with a spicy chilli, or toasted and topped with poached eggs and grilled tomatoes for breakfast Courgette & cheddar cornbread.", img:photo15, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/-OxGhuEk7Q4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:16, title:"Chicken & ham casserole with mustardy dumplings", ingredients:"1 tbsp sunflower oil. 1 tbsp butter. 1 onion, chopped. 2 leeks, thickly sliced. 2 carrots, peeled and chopped. 6 boneless, skinless chicken thighs, cut into chunky pieces. 200ml cider. 800ml hot chicken stock.",describe:"Serve mustardy dumplings with our chicken and ham casserole for a comforting and filling family feast. You can freeze any leftovers, too – if there are any!", img:photo16, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/_xtX64UCgiY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:17, title:"French fries",ingredients:" ⅓ cup white sugar · 2 cups warm water · 2 large russet potatoes - peeled, and sliced into 1/4 inch strips · 6 cups vegetable oil for frying · salt to taste.", describe:"Perfect French fries with our easy recipe – you’ll end up with lightly golden, crisp fries. They’re great as a snack or side dish to a Friday night feast", img:photo17, rate:1, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/hrozhYx_mQE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:18, title:"Spicy nduja arancini",ingredients:"2 tbsp olive oil · 1⁄2 onion, finely chopped · 1 large garlic clove, crushed · 1⁄2 tsp fennel seeds, crushed · 300g risotto rice · ", describe:"Make these moreish rice balls with spicy nduja sausage, gooey mozzarella filling and crunchy breadcrumb coating for a Valentine’s Day nibble", img:photo18, rate:5, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/Po6UzP8lDlg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:19, title:"pasta bake", ingredients:"1 tbsp olive oil · 1 onion, chopped · 1 garlic clove, crushed · 400g can cherry or chopped tomatoes · pinch sugar · few dashes Worcestershire sauce ·",describe:"An Italian-American classic, this freezable sausage pasta bake is an ideal make-ahead family dish for busy days", img:photo19, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/1NYJrpk3QGQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:20, title:"Pasta alla norma", ingredients:"1 tbsp olive oil · 1 onion, chopped · 1 garlic clove, crushed · 400g can cherry or chopped tomatoes · pinch sugar · few dashes Worcestershire sauce ·",describe:"Try this easy version of an alla norma, which uses roast aubergine instead of fried. It’s then tossed with spaghetti and a rich tomato and basil sauce", img:photo20, rate:2, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/pp0vvpkkysE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:21, title:"Gluten-free chocolate cake", ingredients:" ½ cups (320g) granulated sugar. 2 cups (285g) all purpose gluten-free flour blend. ¾ cup (65g) unsweetened cocoa powder. 1 ½ teaspoons (6g) gluten-free baking powder. 1 ½ teaspoons (8g) baking soda. 1 teaspoon salt (6g) 2 large eggs (110g), room temperature.",describe:"Make a dense, rich chocolate cake for a special occasion or anytime treat. While suitable for those following a gluten-free diet, it will prove a hit with everyone", img:photo21, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/bsD4j2rfOjA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:22, title:"Apple & custard rose tart", ingredients:"1 cup (100 g) pecan halves · ⅓ cup (66 g) Redpath® Granulated Sugar · 1 ¼ cups (150 g) all-purpose flour · 1 tsp (6 g) salt · ",describe:"Impress dinner guests with our apple and custard tart. With a homemade pastry base and pretty ‘roses’ topping made from apple, it’s an eye-catching dessert", img:photo22, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/yHdOqwI1DJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:23, title:"Easy blondies", ingredients:"8 tablespoons. (1 stick) unsalted butter, melted and cooled · 1 cup. packed light brown sugar · 1. large egg · 1 teaspoon. vanilla extract.",describe:"Whip up these easy blondies with moreish chunks of white chocolate dotted throughout. These gooey, golden squares are the perfect accompaniment to a cup of tea or coffee", img:photo23, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/Jc5t7CszKCE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:24, title:"Unicorn cake", ingredients:"5 eggs. 155g sugar. 1 teaspoon vanilla extract. 155g plain (all-purpose) flour. Zest of 1 lime. Swiss meringue butter cream. 5 egg whites. 250g caster sugar.",describe:"Stop people in their tracks with a stunning unicorn cake. With a light sponge and salted caramel buttercream, it looks fabulous and tastes divine too", img:photo24, rate:2, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/Xh_Neg-Hp84" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:25, title:"Marzipan chocolate loaf cake", ingredients:"7 to 8 ounces marzipan, chopped into 1/2-inch pieces · 1 tablespoon powdered sugar · 1/2 cup dark chocolate chips · 2 cups all-purpose",describe:"Combine the nutty marzipan flavour with a rich chocolate cake to make the ultimate Easter treat. This easy recipe is perfect for baking with kids", img:photo25, rate:5, link:<iframe width="727" height="409" src="https://www.youtube.com/embed/ph71C0u4Wbw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:26, title:"Sweet potato cheesecake", ingredients:"1 cup (200 g) sugar. ¼ cup (55 g) packed light brown sugar. 1 ¾ cups (270 g) mashed sweet potatoes (see note) 2 large eggs, slightly beaten. ⅔ cup (165 ml) evaporated milk. 2 tablespoons cornstarch. ¼ teaspoon ground cinnamon.",describe:"Layer maple syrup, spiced sweet potato and cool cream cheese on a crushed digestive base to make this dessert. Trust us, it really works", img:photo26, rate:3, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/YoIo3SDw_8A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
    { id:27, title:"Strawberry & elderflower gateau", ingredients:"2 x 200g sponge flan cases (25cm) · 6 tbsp strawberry jam or conserve · 400g strawberries (look for ones that are a similar size), halved ·3 tablespoons elderflower, raspberry, or unseasoned rice vinegar ·",describe:"Make this stunning strawberry and elderflower gateau in just 30 minutes. As well as looking amazing, it tastes as good as anything from a top-end patisserie", img:photo27, rate:4, link:<iframe width="640" height="360" src="https://www.youtube.com/embed/tX1SA5mRlDc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>},
  ]
  const [filtredFood, setFiltredFood] = useState(objFood)

  const handelChange=(item)=>{
  let filter = objFood.filter((val)=>val.title.toLowerCase().includes(item.toLowerCase()));
  console.log(filter)
  setFiltredFood(filter)
  }
  
  const ratingChanged = (newRating) => {
  console.log(newRating)
  let filter = objFood.filter((val)=> val.rate === newRating);
  console.log(filter)
  
  setFiltredFood(filter)
  }

  return (
  <div className="App">
    <img className="img" src={cover} alt="cover" />
  <BrowserRouter>
 <h1 className="Search">  </h1> 
 <Filter changeFn={handelChange} ratingFilter={ratingChanged}/>
  <Switch>
    <Route exact path="/">
    <FoodList obj={filtredFood}/>
    </Route>
    <Route path="/description/:id" render={ (props) => <Description data= {objFood} {...props} />}/>
  </Switch>
  </BrowserRouter>
  </div>
  );
}
export default App;
